// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230607061623_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Venue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ef80d88-5861-4316-ad69-0934f23eee89"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 4, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2405),
                            Description = "Activity 2 months ago",
                            Title = "Past Activity 1",
                            Venue = "Pub"
                        },
                        new
                        {
                            Id = new Guid("e34508c8-9bbd-4491-a274-0a38ff9d4795"),
                            Category = "culture",
                            City = "Paris",
                            Date = new DateTime(2023, 5, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2454),
                            Description = "Activity 1 month ago",
                            Title = "Past Activity 2",
                            Venue = "Louvre"
                        },
                        new
                        {
                            Id = new Guid("66dd8e6e-2cbc-42ae-ab0f-b2a54b2b7ed1"),
                            Category = "culture",
                            City = "London",
                            Date = new DateTime(2023, 7, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2457),
                            Description = "Activity 1 month in future",
                            Title = "Future Activity 1",
                            Venue = "Natural History Museum"
                        },
                        new
                        {
                            Id = new Guid("b7f47c6a-cc93-44d6-a579-114ac80b99b2"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 8, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2459),
                            Description = "Activity 2 months in future",
                            Title = "Future Activity 2",
                            Venue = "O2 Arena"
                        },
                        new
                        {
                            Id = new Guid("1c8ddba4-f744-42a7-b070-abdfd4bfa5f4"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 9, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2462),
                            Description = "Activity 3 months in future",
                            Title = "Future Activity 3",
                            Venue = "Another pub"
                        },
                        new
                        {
                            Id = new Guid("81ff4f47-4a23-4d2b-9484-c2439555d890"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 10, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2467),
                            Description = "Activity 4 months in future",
                            Title = "Future Activity 4",
                            Venue = "Yet another pub"
                        },
                        new
                        {
                            Id = new Guid("51a9e5c7-b810-45b9-a5fe-7c87c4b75efe"),
                            Category = "drinks",
                            City = "London",
                            Date = new DateTime(2023, 11, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2469),
                            Description = "Activity 5 months in future",
                            Title = "Future Activity 5",
                            Venue = "Just another pub"
                        },
                        new
                        {
                            Id = new Guid("54600be9-f204-49cd-b307-c5d96aae9c5f"),
                            Category = "music",
                            City = "London",
                            Date = new DateTime(2023, 12, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2480),
                            Description = "Activity 6 months in future",
                            Title = "Future Activity 6",
                            Venue = "Roundhouse Camden"
                        },
                        new
                        {
                            Id = new Guid("b081ea37-72c7-4cfc-98df-837bc77d6af7"),
                            Category = "travel",
                            City = "London",
                            Date = new DateTime(2024, 1, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2483),
                            Description = "Activity 2 months ago",
                            Title = "Future Activity 7",
                            Venue = "Somewhere on the Thames"
                        },
                        new
                        {
                            Id = new Guid("d46dc6e3-547d-40dc-a306-2237c6fe323a"),
                            Category = "film",
                            City = "London",
                            Date = new DateTime(2024, 2, 7, 6, 16, 23, 688, DateTimeKind.Utc).AddTicks(2486),
                            Description = "Activity 8 months in future",
                            Title = "Future Activity 8",
                            Venue = "Cinema"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
